
name: Build OpenRGB Docker Image

on:
  workflow_dispatch:
    inputs:
      openrgbVersion:
        description: 'OpenRGB Version'
        required: true
        default: 'latest'
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - run: "& ./build.ps1 -Version ${{ inputs.openrgbVersion }} -Push"
        env:
          GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
